Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,12 +7,11 @@ jobs:
     steps:
       - checkout
       - run:
-          name: Create Virtual Environment and Install Dependencies
+          name: Install dependencies
           command: |
             python -m venv venv
             . venv/bin/activate
-            pip install --upgrade pip  # Ensure pip is up to date
-            pip install -r requirements.txt  # Install requirements
+            pip install -r requirements.txt
 
   test:
     docker:
@@ -24,9 +23,8 @@ jobs:
           command: |
             python -m venv venv
             . venv/bin/activate
-            pip install --upgrade pip  # Ensure pip is up to date
-            pip install -r requirements.txt  # Install requirements
-            python -m unittest discover tests  # Discover and run tests
+            pip install -r requirements.txt
+            python -m unittest discover tests
 
   deploy:
     docker:
@@ -39,17 +37,18 @@ jobs:
             echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
             curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
             sudo apt-get update
-            sudo apt-get install google-cloud-sdk
+            sudo apt-get install -y google-cloud-sdk
+
       - run:
-        name: Set up GCloud authentication
-        command: |
-          if [ -z "$IND_KC_GCLOUD_KEY" ]; then
-            echo "Error: IND_KC_GCLOUD_KEY is not set."
-            exit 1
-          fi
-          echo $IND_KC_GCLOUD_KEY | base64 --decode > ${HOME}/gcloud-service-key.json || { echo "Failed to decode IND_KC_GCLOUD_KEY"; exit 1; }
-          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json || { echo "Failed to authenticate with GCloud"; exit 1; }
-          gcloud config set project kc-qa-project || { echo "Failed to set GCloud project"; exit 1; }
+          name: Set up GCloud authentication
+          command: |
+            if [ -z "$IND_KC_GCLOUD_KEY" ]; then
+              echo "Error: IND_KC_GCLOUD_KEY is not set."
+              exit 1
+            fi
+            echo $IND_KC_GCLOUD_KEY | base64 --decode > ${HOME}/gcloud-service-key.json || { echo "Failed to decode IND_KC_GCLOUD_KEY"; exit 1; }
+            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json || { echo "Failed to authenticate with GCloud"; exit 1; }
+            gcloud config set project kc-qa-project || { echo "Failed to set GCloud project"; exit 1; }
 
       - run:
           name: Install Firebase CLI
@@ -66,9 +65,7 @@ workflows:
   build_and_deploy:
     jobs:
       - install
-      - test:
-          requires:
-            - install  # Ensure install job is complete before testing
+      - test
       - deploy:
           requires:
-            - test  # Ensure tests pass before deployment
+            - test
