Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,15 +41,15 @@ jobs:
             sudo apt-get update
             sudo apt-get install google-cloud-sdk
       - run:
-          name: Set up GCloud authentication
-          command: |
+        name: Set up GCloud authentication
+        command: |
           if [ -z "$IND_KC_GCLOUD_KEY" ]; then
             echo "Error: IND_KC_GCLOUD_KEY is not set."
             exit 1
-          command: |
-            echo $IND_KC_GCLOUD_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
-            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
-            gcloud config set project kc-qa-project
+          fi
+          echo $IND_KC_GCLOUD_KEY | base64 --decode > ${HOME}/gcloud-service-key.json || { echo "Failed to decode IND_KC_GCLOUD_KEY"; exit 1; }
+          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json || { echo "Failed to authenticate with GCloud"; exit 1; }
+          gcloud config set project kc-qa-project || { echo "Failed to set GCloud project"; exit 1; }
 
       - run:
           name: Install Firebase CLI
